name: CI - user-service

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    senv:
      DB_USER: user-service
      DB_NAME: users

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Compose
        run: docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build
      - name: Wait for PostgreSQL
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until docker compose exec -T postgres pg_isready --username=$DB_USER --dbname=DB_NAME; do
            echo "Still waiting..."
            sleep 2
          done
          echo "PostgreSQL is ready!"
      - name: Lint the code
        run: docker compose exec -T user-service npm run lint
      - name: Run tests in user-service container
        run: docker compose exec -T user-service npm run test
      - name: Show logs if tests fail
        if: failure()
        run: docker compose logs
      - name: Shut down docker-compose
        run: docker compose down
